
FROM debian:buster

RUN apt update && apt install -y openssh-server rsync sshfs sudo

# necesario para que arranque el proceso sshd
RUN mkdir -p /run/sshd

# añade un usuario admin para facilitar la prueba
RUN useradd -rm -d /home/admin -s /bin/bash -g root -G sudo -u 1000 admin 
RUN echo 'admin:1234' | chpasswd

EXPOSE 22

# arranca el servidor ssh
CMD ["/usr/sbin/sshd","-D"]

# docker build -t openssh-server -f Dockerfile-ssh-server .
# docker run -dit --name servidor-ssh -p 2201:22 openssh-server
