version: "3.9"

services:
  sftp:
    image: atmoz/sftp:alpine
    container_name: servidor-sftp
    ports:
      - "2201:22"
    volumes:
      - ./webapp:/home/admin/var/www/html
    command: admin:1234:1000


